clear
echo -e "\e[97;41m*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*\e[0m"
echo -e "\e[97;41m| El essarrollo de esta terminal |\e[0m"
echo -e "\e[97;41m|    fue posible gracias a:    |\e[0m" 
echo -e "\e[97;41m*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*\e[0m"
echo -e "\e[97;41m| Márquez Sánchez Mirna Daniela |\e[0m"
echo -e "\e[97;41m|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|\e[0m"
echo -e "\e[97;41m| Roldán Montero Hugo Alejandro |\e[0m"
echo -e "\e[97;41m*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*\e[0m"
echo -e "\e[97;41m| Gracias por usar nuestra terminal |\e[0m"
echo -e "\e[97;41m|          Hasta pronto! :)  |\e[0m"
echo -e "\e[97;41m*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*\e[0m"
